apiVersion: v1
kind: Service
metadata:
  name: greeting-endpoint
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: spring-boot-app
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot-deployment
spec:
  selector:
    matchLabels: 
      app: spring-boot-app
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - image: eskaronea/spring_endpoint:latest
        name: greeting-endpoint
        ports:
         - containerPort: 8080
status: {}
