{{- define "bc.default.ports" }}
- name: http
  containerPort: 80
  protocol: TCP
{{- end -}}

{{- define "bc.default.liveness" }}
  tcpSocket:
    port: 80
  initialDelaySeconds: 30
  timeoutSeconds: 15
{{- end -}}

{{- define "bc.default.readiness" }}
  tcpSocket:
    port: 80
  initialDelaySeconds: 30
  periodSeconds: 5
{{- end -}}

{{- define "bc.default.replicas" -}}
${REPLICAS}
{{- end -}}

{{- define "bc.default.affinity" }}
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        - matchExpressions:
          - key: app
            operator: In
            values:
            - reports-
      topologyKey: "kubernetes.io/hostname"
{{- end -}}


#TODO: reports in podAntiAffinity