apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "spring-chart.fullname" . }}
spec:
  selector:
    matchLabels: 
      app: {{ template "spring-chart.name" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "spring-chart.name" . }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Chart.Name }}
        ports:
         - containerPort: 8080
status: {}
