apiVersion: v1
kind: Service
metadata:
  name: {{ template "spring-chart.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app: {{ template "spring-chart.name" . }}
  type: ClusterIP

